### ISSUE TITLE
Clarify install instructions

### ISSUE THREAD

**Issue by danpovey** [RowanHarley/Slither-Server#12]
In your installation instructions, can you please provide a bit more context and indicate basic dependencies?
What platforms do you know are supported, and what needs to installed first?
I have some basic experience with setting up web servers but haven't worked with node.js,

and for instance, on debian if I type
 `apt-cache search npm`

I don't see anything.
I was thinking of setting up the server in the cloud and running the client from home-- do you think this would work potentially?

**Comment by danpovey** [comment]
[OK, I was using an older Debian version, it's in jessie.]

Your installation instructions need to be easier to find, please add a link from README.md.

Please specify what steps people need to do in order to get the server running and connect to it.  Does it have to be from localhost right now?

**Comment by RowanHarley** [comment]
I think localhost is the only way to connect but you could try using your public ip or another ip that could be used for connecting
