### ISSUE TITLE
forceServer not defined

### ISSUE THREAD

**Issue by danpovey** [RowanHarley/Slither-Server#13]
When I opened the javascript console in the current slither.io and typed

```
forceServer("localhost", 8080)
```

it said:

```
VM423:1 Uncaught ReferenceError: forceServer is not defined(…)
```

**Comment by danpovey** [comment]
It seems you have to play the game first and die, and then afterwards, this command works.
I guess it loads the rest of the client code when you play 1st time.

**Comment by RowanHarley** [comment]
It seems to work fine for me when I try the command on first run. Are you sure you aren't getting any errors at the top of the console?

**Comment by danpovey** [comment]
It's possible that having run it wasn't relevant and I had done something
else.
I suspect all this stuff is browser and platform dependent.
When we tried it on IE on Windows it was hard to find the right console, as
the javascript console has all kinds of options where you can select the
javascript running for different tabs and elements.

**Comment by RowanHarley** [comment]
IE isn't compatible with slither.io at the moment. Use Chrome for the best performance
