### ISSUE TITLE
Critical Bug When Trying to Connect (Currently holding back update)

### ISSUE THREAD

**Issue by RowanHarley** [RowanHarley/Slither-Server#4]
I'm having trouble with a bug that closes connections before they can play. If you have any ideas how to fix it, then please comment the solution below or create a pull request

**Comment by RowanHarley** [comment]
The 0.0.2 update will be held back until I find a fix for this bug

**Comment by cswl** [comment]
i'm going offline on SO... so here's the fix if you haven't found it already..
just add `module.exports = arr` at the end of https://github.com/RowanHarley/Slither-Server/blob/master/src/messages/initial.js

**Comment by RowanHarley** [comment]
Thanks @cswl !
