### ISSUE TITLE
How can i connect this server?

### ISSUE THREAD

**Issue by pantez** [RowanHarley/Slither-Server#7]
Hi 
I want to test this slither server but i didn't know how to connect ,what type of client use for connect this server ?

 Best regard.

**Comment by RowanHarley** [comment]
To connect, simply start the server using npm start, then connect using the slither.io website by opening the console and writing `forceServer("localhost", 8080);`

**Comment by goonux** [comment]
root@vps:~/Slither-Server-0.0.5# npm start

> Slither-Server@0.0.5 start /root/Slither-Server-0.0.5
> node ./index.js

/root/Slither-Server-0.0.5/index.js:137
                }
                ^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! Slither-Server@0.0.5 start: `node ./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Slither-Server@0.0.5 start script 'node ./index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Slither-Server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Slither-Server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Slither-Server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/Slither-Server-0.0.5/npm-debug.log


i have got error, somebody help me, how can i fix it ?
